version: '3.8'
services:
  frontend:
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: .
      target: dev
    restart: always
    command: sh -c "node populate-db.ts && yarn dev"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
  backend:
    container_name: backend
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=luxo_task_db
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    # command: node populate-db.ts
